apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "epicode-kb.name" . }}-backend
  labels:
    {{- include "epicode-kb.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "epicode-kb.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "epicode-kb.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ include "epicode-kb.name" . }}-config
            - secretRef:
                name: {{ include "epicode-kb.name" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
