apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "epicode-kb.name" . }}-migrate
  labels:
    {{- include "epicode-kb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "epicode-kb.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          command: ["/app/epicode-kb"]
          envFrom:
            - configMapRef:
                name: {{ include "epicode-kb.name" . }}-config
            - secretRef:
                name: {{ include "epicode-kb.name" . }}-secret
